#ifndef FRMCONSOLE_H
#define FRMCONSOLE_H

#include "wx/wx.h"

//(*Headers(frmConsole)
#include <wx/grid.h>
#include <wx/checkbox.h>
#include <wx/sizer.h>
#include <wx/notebook.h>
#include <wx/button.h>
#include <wx/filedlg.h>
#include <wx/panel.h>
#include <wx/frame.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/choice.h>
#include <wx/html/htmlwin.h>
#include <wx/listbox.h>
//*)

#include <wx/richtext/richtextctrl.h>
#include <wx/mdi.h>
#include <wx/thread.h>
#include <wx/event.h>

#include "pstype.h"
#include <deque>
#include <map>
#include "ibuffer.h"

#include <tr1/functional>
#include <memory.h>
#include <tr1/memory>

typedef std::tr1::function<void (uint32, wxString &)> Action;

class wxCommandValidator : public wxTextValidator
{
public:
  wxCommandValidator(wxWindow *arFocus) : wxTextValidator(wxFILTER_INCLUDE_CHAR_LIST) {
    wxArrayString a;
    wxString s=wxT("QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm1234567890' ,./?!()*\\|{}[]:;=-+_");
    for (uint32 i=0; i<s.Len(); i++) {
      a.Add(wxString(s[i]));
    }
    SetIncludes(a);
  }
};



class frmMain;

class frmConsole: public wxMDIChildFrame
{
  enum EDIRECTION {
    CMD_UP=0,
    CMD_DOWN=1
  };

  std::deque<wxString> lCmdHistory;
  std::deque<wxString>::iterator lastCmd;
  std::map<uint32, uint32> mBaud;

  void ApplyConfig(std::string arXml);
	public:
    frmMain *parent;
		frmConsole(wxMDIParentFrame* parent, wxWindowID id=wxID_ANY);
		virtual ~frmConsole();
    void Output(wxString arText, wxString arColor);

		//(*Declarations(frmConsole)
		wxStaticText* StaticText77;
		wxTextCtrl* tcSocket1DestPort;
		wxStaticText* StaticText114;
		wxStaticText* StaticText152;
		wxStaticText* StaticText17;
		wxChoice* chSocket0Type;
		wxStaticText* StaticText41;
		wxStaticText* StaticText74;
		wxStaticText* StaticText88;
		wxStaticText* StaticText83;
		wxCheckBox* cbVch4Socket7;
		wxTextCtrl* tcVch6DefVipNum;
		wxStaticText* StaticText149;
		wxStaticText* StaticText10;
		wxCheckBox* cbVch2RelayControl;
		wxStaticText* StaticText15;
		wxCheckBox* cbVch2Socket0;
		wxChoice* chSocket3Type;
		wxStaticText* StaticText84;
		wxCheckBox* cbVch1Socket6;
		wxPanel* Panel2;
		wxChoice* chVch3Switch;
		wxCheckBox* cbVch3SerialPort;
		wxNotebook* nbEthernet;
		wxStaticText* StaticText24;
		wxChoice* chVch2DelProto;
		wxCheckBox* cbVch7Socket5;
		wxTextCtrl* tcVch2Interface;
		wxStaticText* StaticText151;
		wxPanel* pVch1;
		wxStaticText* StaticText55;
		wxTextCtrl* tcVch5DefVipNum;
		wxTextCtrl* tcSocket6DestIp;
		wxPanel* pSocket7;
		wxTextCtrl* tcVch1DefVipNum;
		wxChoice* chVch6Switch;
		wxTextCtrl* tcEth1Gateway;
		wxStaticText* StaticText107;
		wxChoice* chVch4Channel;
		wxGrid* gGprs;
		wxStaticText* StaticText92;
		wxStaticText* StaticText32;
		wxChoice* chVch5Switch;
		wxCheckBox* cbSocket7Ndc;
		wxCheckBox* cbVch3Socket0;
		wxStaticText* StaticText172;
		wxCheckBox* cbVch7Socket6;
		wxStaticText* StaticText87;
		wxChoice* chVch5Channel;
		wxGrid* gServer;
		wxListBox* lbScript0;
		wxCheckBox* cbVch6Socket4;
		wxStaticText* StaticText173;
		wxCheckBox* cbVch7SerialPort;
		wxStaticText* StaticText110;
		wxStaticText* StaticText176;
		wxChoice* chVch3Channel;
		wxPanel* pEthernet;
		wxChoice* chVch1DelProto;
		wxStaticText* StaticText115;
		wxCheckBox* cbSocket0Ndc;
		wxStaticText* StaticText129;
		wxTextCtrl* tcVch8RetryTimeout;
		wxCheckBox* cbVch7RelayControl;
		wxChoice* chVch8Switch;
		wxStaticText* StaticText162;
		wxStaticText* StaticText45;
		wxStaticText* StaticText147;
		wxStaticText* StaticText39;
		wxCheckBox* cbVch8Socket4;
		wxTextCtrl* tcSocket5DestPort;
		wxCheckBox* cbVch6Socket5;
		wxPanel* pVch5;
		wxStaticText* StaticText104;
		wxTextCtrl* tcSocket4DestPort;
		wxStaticText* Mask;
		wxTextCtrl* tcVch8ScriptNum;
		wxCheckBox* cbVch2SerialPort;
		wxStaticText* StaticText9;
		wxStaticText* StaticText109;
		wxStaticText* StaticText134;
		wxCheckBox* cbSocket5Ndc;
		wxStaticText* StaticText137;
		wxStaticText* StaticText168;
		wxGrid* gVip;
		wxCheckBox* cbVch6Socket1;
		wxStaticText* StaticText145;
		wxTextCtrl* tcVch7ScriptNum;
		wxStaticText* StaticText148;
		wxTextCtrl* tcVch5Interface;
		wxListBox* lbScript1;
		wxStaticText* StaticText76;
		wxStaticText* StaticText66;
		wxTextCtrl* tcVch5ScriptNum;
		wxButton* bRefresh;
		wxStaticText* StaticText119;
		wxChoice* chSocket2Type;
		wxStaticText* StaticText26;
		wxCheckBox* cbVch4Socket1;
		wxStaticText* StaticText65;
		wxStaticText* StaticText20;
		wxCheckBox* cbVch2Socket3;
		wxStaticText* StaticText57;
		wxChoice* chVch4Switch;
		wxCheckBox* cbVch2Socket2;
		wxStaticText* StaticText25;
		wxChoice* chVch6WorkMode;
		wxTextCtrl* tcVch4Interface;
		wxTextCtrl* tcVch4DefVipNum;
		wxStaticText* StaticText4;
		wxPanel* pSocket1;
		wxListBox* lbScript2;
		wxPanel* pVch8;
		wxCheckBox* cbVch8SerialPort;
		wxStaticText* StaticText97;
		wxCheckBox* cbVch3Socket3;
		wxCheckBox* cbVch3Socket7;
		wxFileDialog* fdUpload;
		wxStaticText* StaticText43;
		wxStaticText* StaticText170;
		wxTextCtrl* tcEth0Mac;
		wxCheckBox* cbVch1Socket3;
		wxCheckBox* cbVch7Socket1;
		wxStaticText* StaticText117;
		wxStaticText* StaticText30;
		wxChoice* chVch8Channel;
		wxTextCtrl* tcVch2WndSize;
		wxTextCtrl* tcVch5RetryTimeout;
		wxCheckBox* cbVch8Socket6;
		wxTextCtrl* tcVch6RetryCnt;
		wxStaticText* StaticText98;
		wxStaticText* StaticText64;
		wxCheckBox* cbVch8Socket3;
		wxCheckBox* cbVch8Socket2;
		wxCheckBox* cbVch6Socket3;
		wxStaticText* StaticText120;
		wxCheckBox* cbVch8Socket7;
		wxChoice* chVch5WorkMode;
		wxCheckBox* cbVch2Socket4;
		wxChoice* chVch1WorkMode;
		wxTextCtrl* tcVch3RetryCnt;
		wxCheckBox* cbSocket4Ndc;
		wxStaticText* StaticText12;
		wxTextCtrl* tcVch7RetryCnt;
		wxStaticText* StaticText156;
		wxCheckBox* cbVch6Socket2;
		wxTextCtrl* tcVch6ScriptNum;
		wxStaticText* StaticText46;
		wxCheckBox* cbVch6RelayControl;
		wxCheckBox* cbVch5Socket3;
		wxStaticText* StaticText8;
		wxButton* bDownload;
		wxTextCtrl* tcVch3DefVipNum;
		wxChoice* chVch2Channel;
		wxStaticText* IPAddress;
		wxNotebook* nbConfig;
		wxStaticText* StaticText38;
		wxTextCtrl* tcSocket4LocalPort;
		wxStaticText* StaticText62;
		wxTextCtrl* tcVch4RetryCnt;
		wxStaticText* StaticText34;
		wxStaticText* StaticText177;
		wxStaticText* StaticText155;
		wxStaticText* StaticText93;
		wxStaticText* StaticText136;
		wxCheckBox* cbVch3Socket6;
		wxTextCtrl* tcSocket2LocalPort;
		wxTextCtrl* tcSocket6DestPort;
		wxNotebook* nbSocketEth1;
		wxTextCtrl* tcSocket0DestIp;
		wxChoice* chDebug;
		wxTextCtrl* tcSocket2DestIp;
		wxStaticText* StaticText58;
		wxPanel* pSocket0;
		wxCheckBox* cbVch1Socket1;
		wxStaticText* StaticText16;
		wxStaticText* StaticText165;
		wxStaticText* StaticText79;
		wxStaticText* StaticText22;
		wxStaticText* StaticText85;
		wxTextCtrl* tcVch3RetryTimeout;
		wxTextCtrl* tcCommand;
		wxStaticText* StaticText60;
		wxStaticText* StaticText21;
		wxStaticText* StaticText19;
		wxStaticText* StaticText94;
		wxStaticText* StaticText67;
		wxTextCtrl* tcVch3Interface;
		wxCheckBox* cbVch3Socket1;
		wxStaticText* StaticText143;
		wxStaticText* StaticText59;
		wxStaticText* StaticText70;
		wxGridSizer* GridSizer2;
		wxStaticText* StaticText105;
		wxTextCtrl* tcSocket0LocalPort;
		wxStaticText* StaticText128;
		wxListBox* lbScript3;
		wxCheckBox* cbVch4Socket0;
		wxStaticText* StaticText133;
		wxPanel* pVip;
		wxCheckBox* cbVch2Socket6;
		wxChoice* chFlowCtrl;
		wxChoice* chVch5DelProto;
		wxTextCtrl* tcSocket7DestIp;
		wxTextCtrl* tcVch1Interface;
		wxStaticText* StaticText159;
		wxStaticText* StaticText96;
		wxCheckBox* cbVch5Socket5;
		wxStaticText* StaticText81;
		wxStaticText* StaticText123;
		wxStaticText* StaticText95;
		wxStaticText* StaticText157;
		wxTextCtrl* tcMaxIpPwrDelay;
		wxNotebook* nbVch;
		wxStaticText* StaticText160;
		wxStaticText* StaticText125;
		wxCheckBox* cbVch8Socket0;
		wxStaticText* StaticText163;
		wxStaticText* StaticText178;
		wxTextCtrl* tcVch8DefVipNum;
		wxTextCtrl* tcVch4WndSize;
		wxTextCtrl* tcSocket3DestPort;
		wxCheckBox* cbVch4RelayControl;
		wxTextCtrl* tcEth0Mask;
		wxNotebook* Notebook1;
		wxStaticText* StaticText2;
		wxChoice* chVch4WorkMode;
		wxStaticText* StaticText131;
		wxTextCtrl* tcEth1Mask;
		wxCheckBox* cbVch5Socket0;
		wxStaticText* StaticText141;
		wxStaticText* StaticText101;
		wxStaticText* StaticText7;
		wxStaticText* StaticText73;
		wxCheckBox* cbVch2Socket7;
		wxChoice* chBaud;
		wxCheckBox* cbVch1Socket5;
		wxCheckBox* cbVch6Socket6;
		wxTextCtrl* tcEth1Ip;
		wxStaticText* StaticText138;
		wxStaticText* StaticText144;
		wxChoice* chVch8DelProto;
		wxStaticText* StaticText61;
		wxCheckBox* cbVch4Socket3;
		wxStaticText* StaticText102;
		wxTextCtrl* tcEth0Ip;
		wxTextCtrl* tcSocket4DestIp;
		wxStaticText* StaticText167;
		wxStaticText* StaticText27;
		wxCheckBox* cbVch8Socket1;
		wxStaticText* StaticText124;
		wxTextCtrl* tcVch3RelayTime;
		wxStaticText* StaticText169;
		wxChoice* chVch2WorkMode;
		wxStaticText* StaticText82;
		wxTextCtrl* tcVch2DefVipNum;
		wxStaticText* StaticText36;
		wxCheckBox* cbVch7Socket4;
		wxPanel* pSocket5;
		wxChoice* chSocket1Type;
		wxStaticText* StaticText175;
		wxChoice* chVch1Channel;
		wxChoice* chVch8WorkMode;
		wxCheckBox* cbVch3Socket2;
		wxStaticText* StaticText33;
		wxChoice* chVch2Switch;
		wxCheckBox* cbVch1RelayControl;
		wxStaticText* StaticText69;
		wxTextCtrl* tcGprsConnTimeout;
		wxChoice* chVch4DelProto;
		wxStaticText* StaticText37;
		wxStaticText* StaticText68;
		wxStaticText* StaticText99;
		wxCheckBox* cbVch2Socket1;
		wxStaticText* StaticText49;
		wxCheckBox* cbVch1Socket4;
		wxStaticText* StaticText52;
		wxTextCtrl* tcVch1RetryTimeout;
		wxCheckBox* cbVch2Socket5;
		wxCheckBox* cbVch1SerialPort;
		wxStaticText* StaticText103;
		wxCheckBox* cbVch5SerialPort;
		wxPanel* pSocket6;
		wxStaticText* StaticText179;
		wxStaticText* StaticText108;
		wxCheckBox* cbVch5Socket1;
		wxTextCtrl* tcIpConnTimeout;
		wxStaticText* StaticText121;
		wxTextCtrl* tcVch3WndSize;
		wxStaticText* StaticText127;
		wxTextCtrl* tcVch6RelayTime;
		wxCheckBox* cbVch5Socket4;
		wxStaticText* StaticText54;
		wxStaticText* StaticText28;
		wxTextCtrl* tcSocket5LocalPort;
		wxTextCtrl* tcEth1Mac;
		wxStaticText* StaticText150;
		wxStaticText* StaticText44;
		wxPanel* pGprs;
		wxStaticText* StaticText174;
		wxCheckBox* cbVch3RelayControl;
		wxTextCtrl* tcTraceAnswer;
		wxStaticText* StaticText72;
		wxChoice* chVch3DelProto;
		wxStaticText* StaticText18;
		wxTextCtrl* tcVch4RetryTimeout;
		wxTextCtrl* tcSocket2DestPort;
		wxStaticText* StaticText132;
		wxCheckBox* cbVch7Socket0;
		wxButton* bUpload;
		wxStaticText* StaticText80;
		wxTextCtrl* tcVch4RelayTime;
		wxTextCtrl* tcVch5RetryCnt;
		wxCheckBox* cbVch4Socket4;
		wxTextCtrl* tcVch1WndSize;
		wxPanel* pEthernet1;
		wxNotebook* nbSocketEth0;
		wxCheckBox* cbSocket2Ndc;
		wxTextCtrl* tcVch7WndSize;
		wxCheckBox* cbVch5RelayControl;
		wxStaticText* StaticText116;
		wxStaticText* StaticText166;
		wxTextCtrl* tcSocket7DestPort;
		wxTextCtrl* tcIpPacketMaxLen;
		wxCheckBox* cbVch8RelayControl;
		wxCheckBox* cbVch5Socket6;
		wxPanel* pSocket2;
		wxCheckBox* cbVch8Socket5;
		wxCheckBox* cbVch4Socket2;
		wxStaticText* StaticText31;
		wxStaticText* StaticText51;
		wxTextCtrl* tcVch8RelayTime;
		wxChoice* chVch1Switch;
		wxTextCtrl* tcVch6RetryTimeout;
		wxTextCtrl* tcVch4ScriptNum;
		wxChoice* chSocket7Type;
		wxStaticText* StaticText140;
		wxChoice* chVch3WorkMode;
		wxCheckBox* cbVch5Socket7;
		wxTextCtrl* tcSocket5DestIp;
		wxStaticText* StaticText56;
		wxStaticText* StaticText100;
		wxStaticText* StaticText161;
		wxStaticText* StaticText126;
		wxCheckBox* cbSocket3Ndc;
		wxCheckBox* cbVch7Socket2;
		wxStaticText* StaticText158;
		wxTextCtrl* tcSocket7LocalPort;
		wxStaticText* StaticText90;
		wxStaticText* StaticText130;
		wxStaticText* StaticText40;
		wxTextCtrl* tcVch1RelayTime;
		wxChoice* chSocket6Type;
		wxTextCtrl* tcVch5WndSize;
		wxStaticText* StaticText42;
		wxPanel* pVch4;
		wxStaticText* StaticText53;
		wxCheckBox* cbVch1Socket7;
		wxTextCtrl* tcVch2RetryCnt;
		wxStaticText* StaticText23;
		wxStaticText* StaticText5;
		wxTextCtrl* tcSocket0DestPort;
		wxStaticText* StaticText29;
		wxStaticText* StaticText154;
		wxTextCtrl* tcVch7DefVipNum;
		wxCheckBox* cbVch4Socket5;
		wxStaticText* StaticText153;
		wxStaticText* StaticText48;
		wxCheckBox* cbVch3Socket4;
		wxStaticText* StaticText112;
		wxStaticText* StaticText47;
		wxStaticText* StaticText71;
		wxStaticText* StaticText3;
		wxPanel* pVch7;
		wxTextCtrl* tcVch7RelayTime;
		wxCheckBox* cbVch7Socket3;
		wxCheckBox* cbVch1Socket2;
		wxStaticText* StaticText113;
		wxStaticText* StaticText122;
		wxTextCtrl* tcVch8WndSize;
		wxPanel* pVch6;
		wxStaticText* StaticText139;
		wxPanel* pVch;
		wxPanel* pServer;
		wxTextCtrl* tcVch1RetryCnt;
		wxChoice* chVch7Channel;
		wxTextCtrl* tcVch1ScriptNum;
		wxTextCtrl* tcVch2RelayTime;
		wxStaticText* StaticText78;
		wxCheckBox* cbVch4SerialPort;
		wxStaticText* StaticText6;
		wxStaticText* StaticText111;
		wxStaticText* StaticText63;
		wxTextCtrl* tcSocket3LocalPort;
		wxTextCtrl* tcVch6Interface;
		wxHtmlWindow* htmlOut;
		wxTextCtrl* tcVch6WndSize;
		wxTextCtrl* tcSocket1LocalPort;
		wxTextCtrl* tcVch7Interface;
		wxPanel* pVch3;
		wxStaticText* StaticText118;
		wxStaticText* StaticText35;
		wxCheckBox* cbVch1Socket0;
		wxPanel* pSocket4;
		wxPanel* pEthernet0;
		wxStaticText* StaticText50;
		wxTextCtrl* tcNode;
		wxTextCtrl* tcVch8RetryCnt;
		wxTextCtrl* tcVch7RetryTimeout;
		wxStaticText* StaticText86;
		wxChoice* chVch7WorkMode;
		wxStaticText* StaticText11;
		wxPanel* pSerial;
		wxChoice* chChanPrior;
		wxStaticText* StaticText14;
		wxTextCtrl* tcEth0Gateway;
		wxCheckBox* cbSocket6Ndc;
		wxCheckBox* cbSocket1Ndc;
		wxTextCtrl* tcVch2ScriptNum;
		wxStaticText* StaticText;
		wxPanel* pGeneral;
		wxStaticText* StaticText13;
		wxStaticText* StaticText142;
		wxStaticText* StaticText1;
		wxPanel* Panel1;
		wxStaticText* StaticText135;
		wxChoice* chVch6Channel;
		wxTextCtrl* tcCSQMinVal;
		wxTextCtrl* tcVch8Interface;
		wxTextCtrl* tcVch2RetryTimeout;
		wxCheckBox* cbVch6Socket7;
		wxChoice* chVch7Switch;
		wxStaticText* StaticText75;
		wxCheckBox* cbVch6Socket0;
		wxStaticText* StaticText171;
		wxTextCtrl* tcSocket1DestIp;
		wxChoice* chSocket4Type;
		wxCheckBox* cbVch7Socket7;
		wxTextCtrl* tcSocket6LocalPort;
		wxPanel* pVch2;
		wxStaticText* StaticText91;
		wxTextCtrl* tcVch3ScriptNum;
		wxTextCtrl* tcSocket3DestIp;
		wxStaticText* StaticText106;
		wxPanel* pSocket3;
		wxTextCtrl* tcVch5RelayTime;
		wxStaticText* StaticText146;
		wxStaticText* StaticText164;
		wxCheckBox* cbVch4Socket6;
		wxCheckBox* cbVch3Socket5;
		wxPanel* pScripts;
		wxCheckBox* cbVch6SerialPort;
		wxChoice* chVch6DelProto;
		wxChoice* chVch7DelProto;
		wxChoice* chSocket5Type;
		wxCheckBox* cbVch5Socket2;
		wxStaticText* StaticText89;
		//*)

    uint32 RemoteNode;
		static const long ID_OUT;

	protected:

		//(*Identifiers(frmConsole)
		static const long ID_TEXTCTRL1;
		static const long ID_BUTTON3;
		static const long ID_BUTTON2;
		static const long ID_HTMLWINDOW1;
		static const long ID_PANEL1;
		static const long ID_BUTTON1;
		static const long ID_STATICTEXT1;
		static const long ID_TEXTCTRL3;
		static const long ID_STATICTEXT2;
		static const long ID_TEXTCTRL4;
		static const long ID_STATICTEXT3;
		static const long ID_TEXTCTRL5;
		static const long ID_STATICTEXT4;
		static const long ID_TEXTCTRL6;
		static const long ID_STATICTEXT5;
		static const long ID_TEXTCTRL7;
		static const long ID_STATICTEXT6;
		static const long ID_TEXTCTRL8;
		static const long ID_STATICTEXT7;
		static const long ID_CHOICE1;
		static const long ID_STATICTEXT8;
		static const long ID_CHOICE2;
		static const long ID_PANEL3;
		static const long ID_GRID1;
		static const long ID_PANEL4;
		static const long ID_GRID2;
		static const long ID_PANEL5;
		static const long ID_GRID3;
		static const long ID_PANEL6;
		static const long ID_STATICTEXT9;
		static const long ID_LBSCRIPT0;
		static const long ID_STATICTEXT10;
		static const long ID_LBSCRIPT1;
		static const long ID_STATICTEXT11;
		static const long ID_LBSCRIPT2;
		static const long ID_STATICTEXT12;
		static const long ID_LBSCRIPT3;
		static const long ID_PANEL7;
		static const long ID_STATICTEXT13;
		static const long ID_CHOICE3;
		static const long ID_STATICTEXT14;
		static const long ID_CHOICE4;
		static const long ID_PANEL8;
		static const long ID_STATICTEXT15;
		static const long ID_TEXTCTRL9;
		static const long ID_STATICTEXT16;
		static const long ID_TEXTCTRL10;
		static const long ID_STATICTEXT17;
		static const long ID_TEXTCTRL11;
		static const long ID_STATICTEXT18;
		static const long ID_TEXTCTRL12;
		static const long ID_STATICTEXT19;
		static const long ID_CHOICE5;
		static const long ID_STATICTEXT20;
		static const long ID_TEXTCTRL14;
		static const long ID_STATICTEXT23;
		static const long ID_TEXTCTRL15;
		static const long ID_STATICTEXT21;
		static const long ID_TEXTCTRL13;
		static const long ID_STATICTEXT22;
		static const long ID_CHECKBOX1;
		static const long ID_PANEL13;
		static const long ID_STATICTEXT24;
		static const long ID_CHOICE6;
		static const long ID_STATICTEXT25;
		static const long ID_TEXTCTRL17;
		static const long ID_STATICTEXT28;
		static const long ID_TEXTCTRL18;
		static const long ID_STATICTEXT26;
		static const long ID_TEXTCTRL16;
		static const long ID_STATICTEXT27;
		static const long ID_CHECKBOX2;
		static const long ID_PANEL14;
		static const long ID_STATICTEXT29;
		static const long ID_CHOICE7;
		static const long ID_STATICTEXT30;
		static const long ID_TEXTCTRL20;
		static const long ID_STATICTEXT33;
		static const long ID_TEXTCTRL21;
		static const long ID_STATICTEXT31;
		static const long ID_TEXTCTRL19;
		static const long ID_STATICTEXT32;
		static const long ID_CHECKBOX3;
		static const long ID_PANEL15;
		static const long ID_STATICTEXT34;
		static const long ID_CHOICE8;
		static const long ID_STATICTEXT35;
		static const long ID_TEXTCTRL23;
		static const long ID_STATICTEXT38;
		static const long ID_TEXTCTRL24;
		static const long ID_STATICTEXT36;
		static const long ID_TEXTCTRL22;
		static const long ID_STATICTEXT37;
		static const long ID_CHECKBOX4;
		static const long ID_PANEL16;
		static const long ID_NOTEBOOK4;
		static const long ID_PANEL11;
		static const long ID_STATICTEXT39;
		static const long ID_TEXTCTRL25;
		static const long ID_STATICTEXT40;
		static const long ID_TEXTCTRL26;
		static const long ID_STATICTEXT41;
		static const long ID_TEXTCTRL27;
		static const long ID_STATICTEXT42;
		static const long ID_TEXTCTRL28;
		static const long ID_STATICTEXT43;
		static const long ID_CHOICE9;
		static const long ID_STATICTEXT44;
		static const long ID_TEXTCTRL30;
		static const long ID_STATICTEXT47;
		static const long ID_TEXTCTRL31;
		static const long ID_STATICTEXT45;
		static const long ID_TEXTCTRL29;
		static const long ID_STATICTEXT46;
		static const long ID_CHECKBOX5;
		static const long ID_PANEL17;
		static const long ID_STATICTEXT48;
		static const long ID_CHOICE10;
		static const long ID_STATICTEXT49;
		static const long ID_TEXTCTRL33;
		static const long ID_STATICTEXT52;
		static const long ID_TEXTCTRL34;
		static const long ID_STATICTEXT50;
		static const long ID_TEXTCTRL32;
		static const long ID_STATICTEXT51;
		static const long ID_CHECKBOX6;
		static const long ID_PANEL18;
		static const long ID_STATICTEXT53;
		static const long ID_CHOICE11;
		static const long ID_STATICTEXT54;
		static const long ID_TEXTCTRL36;
		static const long ID_STATICTEXT57;
		static const long ID_TEXTCTRL37;
		static const long ID_STATICTEXT55;
		static const long ID_TEXTCTRL35;
		static const long ID_STATICTEXT56;
		static const long ID_CHECKBOX7;
		static const long ID_PANEL19;
		static const long ID_STATICTEXT58;
		static const long ID_CHOICE12;
		static const long ID_STATICTEXT59;
		static const long ID_TEXTCTRL39;
		static const long ID_STATICTEXT62;
		static const long ID_TEXTCTRL40;
		static const long ID_STATICTEXT60;
		static const long ID_TEXTCTRL38;
		static const long ID_STATICTEXT61;
		static const long ID_CHECKBOX8;
		static const long ID_PANEL20;
		static const long ID_NOTEBOOK5;
		static const long ID_PANEL12;
		static const long ID_NOTEBOOK3;
		static const long ID_PANEL9;
		static const long ID_CHOICE13;
		static const long ID_STATICTEXT63;
		static const long ID_CHOICE14;
		static const long ID_STATICTEXT64;
		static const long ID_TEXTCTRL41;
		static const long ID_STATICTEXT65;
		static const long ID_TEXTCTRL42;
		static const long ID_STATICTEXT66;
		static const long ID_TEXTCTRL43;
		static const long ID_STATICTEXT67;
		static const long ID_CHOICE15;
		static const long ID_CHECKBOX18;
		static const long ID_TEXTCTRL47;
		static const long ID_STATICTEXT77;
		static const long ID_STATICTEXT68;
		static const long ID_STATICTEXT69;
		static const long ID_CHOICE16;
		static const long ID_STATICTEXT70;
		static const long ID_STATICTEXT71;
		static const long ID_TEXTCTRL44;
		static const long ID_STATICTEXT72;
		static const long ID_TEXTCTRL45;
		static const long ID_STATICTEXT73;
		static const long ID_TEXTCTRL46;
		static const long ID_STATICTEXT74;
		static const long ID_STATICTEXT75;
		static const long ID_CHECKBOX9;
		static const long ID_STATICTEXT76;
		static const long ID_CHECKBOX10;
		static const long ID_CHECKBOX11;
		static const long ID_CHECKBOX12;
		static const long ID_CHECKBOX13;
		static const long ID_CHECKBOX14;
		static const long ID_CHECKBOX15;
		static const long ID_CHECKBOX16;
		static const long ID_CHECKBOX17;
		static const long ID_PANEL21;
		static const long ID_CHOICE17;
		static const long ID_STATICTEXT78;
		static const long ID_CHOICE18;
		static const long ID_STATICTEXT79;
		static const long ID_TEXTCTRL48;
		static const long ID_STATICTEXT80;
		static const long ID_TEXTCTRL49;
		static const long ID_STATICTEXT81;
		static const long ID_TEXTCTRL50;
		static const long ID_STATICTEXT82;
		static const long ID_CHOICE19;
		static const long ID_CHECKBOX19;
		static const long ID_TEXTCTRL51;
		static const long ID_STATICTEXT83;
		static const long ID_STATICTEXT84;
		static const long ID_STATICTEXT85;
		static const long ID_CHOICE20;
		static const long ID_STATICTEXT86;
		static const long ID_STATICTEXT87;
		static const long ID_TEXTCTRL52;
		static const long ID_STATICTEXT88;
		static const long ID_TEXTCTRL53;
		static const long ID_STATICTEXT89;
		static const long ID_TEXTCTRL54;
		static const long ID_STATICTEXT90;
		static const long ID_STATICTEXT91;
		static const long ID_CHECKBOX20;
		static const long ID_STATICTEXT92;
		static const long ID_CHECKBOX21;
		static const long ID_CHECKBOX22;
		static const long ID_CHECKBOX23;
		static const long ID_CHECKBOX24;
		static const long ID_CHECKBOX25;
		static const long ID_CHECKBOX26;
		static const long ID_CHECKBOX27;
		static const long ID_CHECKBOX28;
		static const long ID_PANEL22;
		static const long ID_CHOICE21;
		static const long ID_STATICTEXT93;
		static const long ID_CHOICE22;
		static const long ID_STATICTEXT94;
		static const long ID_TEXTCTRL55;
		static const long ID_STATICTEXT95;
		static const long ID_TEXTCTRL56;
		static const long ID_STATICTEXT96;
		static const long ID_TEXTCTRL57;
		static const long ID_STATICTEXT97;
		static const long ID_CHOICE23;
		static const long ID_CHECKBOX29;
		static const long ID_TEXTCTRL58;
		static const long ID_STATICTEXT98;
		static const long ID_STATICTEXT99;
		static const long ID_STATICTEXT100;
		static const long ID_CHOICE24;
		static const long ID_STATICTEXT101;
		static const long ID_STATICTEXT102;
		static const long ID_TEXTCTRL59;
		static const long ID_STATICTEXT103;
		static const long ID_TEXTCTRL60;
		static const long ID_STATICTEXT104;
		static const long ID_TEXTCTRL61;
		static const long ID_STATICTEXT105;
		static const long ID_STATICTEXT106;
		static const long ID_CHECKBOX30;
		static const long ID_STATICTEXT107;
		static const long ID_CHECKBOX31;
		static const long ID_CHECKBOX32;
		static const long ID_CHECKBOX33;
		static const long ID_CHECKBOX34;
		static const long ID_CHECKBOX35;
		static const long ID_CHECKBOX36;
		static const long ID_CHECKBOX37;
		static const long ID_CHECKBOX38;
		static const long ID_PANEL23;
		static const long ID_CHOICE25;
		static const long ID_STATICTEXT108;
		static const long ID_CHOICE26;
		static const long ID_STATICTEXT109;
		static const long ID_TEXTCTRL62;
		static const long ID_STATICTEXT110;
		static const long ID_TEXTCTRL63;
		static const long ID_STATICTEXT111;
		static const long ID_TEXTCTRL64;
		static const long ID_STATICTEXT112;
		static const long ID_CHOICE27;
		static const long ID_CHECKBOX39;
		static const long ID_TEXTCTRL65;
		static const long ID_STATICTEXT113;
		static const long ID_STATICTEXT114;
		static const long ID_STATICTEXT115;
		static const long ID_CHOICE28;
		static const long ID_STATICTEXT116;
		static const long ID_STATICTEXT117;
		static const long ID_TEXTCTRL66;
		static const long ID_STATICTEXT118;
		static const long ID_TEXTCTRL67;
		static const long ID_STATICTEXT119;
		static const long ID_TEXTCTRL68;
		static const long ID_STATICTEXT120;
		static const long ID_STATICTEXT121;
		static const long ID_CHECKBOX40;
		static const long ID_STATICTEXT122;
		static const long ID_CHECKBOX41;
		static const long ID_CHECKBOX42;
		static const long ID_CHECKBOX43;
		static const long ID_CHECKBOX44;
		static const long ID_CHECKBOX45;
		static const long ID_CHECKBOX46;
		static const long ID_CHECKBOX47;
		static const long ID_CHECKBOX48;
		static const long ID_PANEL24;
		static const long ID_CHOICE29;
		static const long ID_STATICTEXT123;
		static const long ID_CHOICE30;
		static const long ID_STATICTEXT124;
		static const long ID_TEXTCTRL69;
		static const long ID_STATICTEXT125;
		static const long ID_TEXTCTRL70;
		static const long ID_STATICTEXT126;
		static const long ID_TEXTCTRL71;
		static const long ID_STATICTEXT127;
		static const long ID_CHOICE31;
		static const long ID_CHECKBOX49;
		static const long ID_TEXTCTRL72;
		static const long ID_STATICTEXT128;
		static const long ID_STATICTEXT129;
		static const long ID_STATICTEXT130;
		static const long ID_CHOICE32;
		static const long ID_STATICTEXT131;
		static const long ID_STATICTEXT132;
		static const long ID_TEXTCTRL73;
		static const long ID_STATICTEXT133;
		static const long ID_TEXTCTRL74;
		static const long ID_STATICTEXT134;
		static const long ID_TEXTCTRL75;
		static const long ID_STATICTEXT135;
		static const long ID_STATICTEXT136;
		static const long ID_CHECKBOX50;
		static const long ID_STATICTEXT137;
		static const long ID_CHECKBOX51;
		static const long ID_CHECKBOX52;
		static const long ID_CHECKBOX53;
		static const long ID_CHECKBOX54;
		static const long ID_CHECKBOX55;
		static const long ID_CHECKBOX56;
		static const long ID_CHECKBOX57;
		static const long ID_CHECKBOX58;
		static const long ID_PANEL25;
		static const long ID_CHOICE33;
		static const long ID_STATICTEXT138;
		static const long ID_CHOICE34;
		static const long ID_STATICTEXT139;
		static const long ID_TEXTCTRL76;
		static const long ID_STATICTEXT140;
		static const long ID_TEXTCTRL77;
		static const long ID_STATICTEXT141;
		static const long ID_TEXTCTRL78;
		static const long ID_STATICTEXT142;
		static const long ID_CHOICE35;
		static const long ID_CHECKBOX59;
		static const long ID_TEXTCTRL79;
		static const long ID_STATICTEXT143;
		static const long ID_STATICTEXT144;
		static const long ID_STATICTEXT145;
		static const long ID_CHOICE36;
		static const long ID_STATICTEXT146;
		static const long ID_STATICTEXT147;
		static const long ID_TEXTCTRL80;
		static const long ID_STATICTEXT148;
		static const long ID_TEXTCTRL81;
		static const long ID_STATICTEXT149;
		static const long ID_TEXTCTRL82;
		static const long ID_STATICTEXT150;
		static const long ID_STATICTEXT151;
		static const long ID_CHECKBOX60;
		static const long ID_STATICTEXT152;
		static const long ID_CHECKBOX61;
		static const long ID_CHECKBOX62;
		static const long ID_CHECKBOX63;
		static const long ID_CHECKBOX64;
		static const long ID_CHECKBOX65;
		static const long ID_CHECKBOX66;
		static const long ID_CHECKBOX67;
		static const long ID_CHECKBOX68;
		static const long ID_PANEL26;
		static const long ID_CHOICE37;
		static const long ID_STATICTEXT153;
		static const long ID_CHOICE38;
		static const long ID_STATICTEXT154;
		static const long ID_TEXTCTRL83;
		static const long ID_STATICTEXT155;
		static const long ID_TEXTCTRL84;
		static const long ID_STATICTEXT156;
		static const long ID_TEXTCTRL85;
		static const long ID_STATICTEXT157;
		static const long ID_CHOICE39;
		static const long ID_CHECKBOX69;
		static const long ID_TEXTCTRL86;
		static const long ID_STATICTEXT158;
		static const long ID_STATICTEXT159;
		static const long ID_STATICTEXT160;
		static const long ID_CHOICE40;
		static const long ID_STATICTEXT161;
		static const long ID_STATICTEXT162;
		static const long ID_TEXTCTRL87;
		static const long ID_STATICTEXT163;
		static const long ID_TEXTCTRL88;
		static const long ID_STATICTEXT164;
		static const long ID_TEXTCTRL89;
		static const long ID_STATICTEXT165;
		static const long ID_STATICTEXT166;
		static const long ID_CHECKBOX70;
		static const long ID_STATICTEXT167;
		static const long ID_CHECKBOX71;
		static const long ID_CHECKBOX72;
		static const long ID_CHECKBOX73;
		static const long ID_CHECKBOX74;
		static const long ID_CHECKBOX75;
		static const long ID_CHECKBOX76;
		static const long ID_CHECKBOX77;
		static const long ID_CHECKBOX78;
		static const long ID_PANEL27;
		static const long ID_CHOICE41;
		static const long ID_STATICTEXT168;
		static const long ID_CHOICE42;
		static const long ID_STATICTEXT169;
		static const long ID_TEXTCTRL90;
		static const long ID_STATICTEXT170;
		static const long ID_TEXTCTRL91;
		static const long ID_STATICTEXT171;
		static const long ID_TEXTCTRL92;
		static const long ID_STATICTEXT172;
		static const long ID_CHOICE43;
		static const long ID_CHECKBOX79;
		static const long ID_TEXTCTRL93;
		static const long ID_STATICTEXT173;
		static const long ID_STATICTEXT174;
		static const long ID_STATICTEXT175;
		static const long ID_CHOICE44;
		static const long ID_STATICTEXT176;
		static const long ID_STATICTEXT177;
		static const long ID_TEXTCTRL94;
		static const long ID_STATICTEXT178;
		static const long ID_TEXTCTRL95;
		static const long ID_STATICTEXT179;
		static const long ID_TEXTCTRL96;
		static const long ID_STATICTEXT180;
		static const long ID_STATICTEXT181;
		static const long ID_CHECKBOX80;
		static const long ID_STATICTEXT182;
		static const long ID_CHECKBOX81;
		static const long ID_CHECKBOX82;
		static const long ID_CHECKBOX83;
		static const long ID_CHECKBOX84;
		static const long ID_CHECKBOX85;
		static const long ID_CHECKBOX86;
		static const long ID_CHECKBOX87;
		static const long ID_CHECKBOX88;
		static const long ID_PANEL28;
		static const long ID_NOTEBOOK6;
		static const long ID_PANEL10;
		static const long ID_NOTEBOOK2;
		static const long ID_PANEL2;
		static const long ID_NOTEBOOK1;
		static const long ID_TEXTCTRL2;
		//*)

	private:

		//(*Handlers(frmConsole)
		void OntcNodeTextEnter(wxCommandEvent& event);
		void OnPaint(wxPaintEvent& event);
		void OntcCommandTextEnter(wxCommandEvent& event);
		void OnKeyDown(wxKeyEvent& event);
		void OnbRefreshConfigClick(wxCommandEvent& event);
		void OnNotebook1PageChanged(wxNotebookEvent& event);
		void OnbUploadClick(wxCommandEvent& event);
		void OnnbConfigPageChanged(wxNotebookEvent& event);
		void OntcNodeText(wxCommandEvent& event);
		//*)

    //void OnAction(uint32 arInterface, wxString &arStr);
    void OnAction(wxThreadEvent& event);
    void OnOut100(wxThreadEvent& event);
    void OnOut103(wxThreadEvent& event);
    void getCommandHistory(EDIRECTION arDir);

    void EnableControls();
    void DisableControls();

		DECLARE_EVENT_TABLE()
};

#endif
